// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID          int64
	UserID      int64
	Title       string
	Description string
	Status      string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type User struct {
	ID           int64
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
}
